image: docker:29.3.1-cli

services:
  - docker:29.3.1-dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  FF_NETWORK_PER_BUILD: "true"

stages:
  - build
  - notification


default:
  before_script:
    - 'echo "Registry URL: $CI_REGISTRY"'
    - 'echo "Registry User: $CI_REGISTRY_USER"'
    - 'echo "Registry Image: $CI_REGISTRY_IMAGE"'
    - 'echo "Project Path: $CI_PROJECT_PATH"'


build:
  stage: build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - 'echo "Building image: $CI_REGISTRY_IMAGE:latest"'
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker tag "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success

success_notification:
  stage: notification
  script:
    - apk add curl git
    - wget https://gitlab.mdbook.me/mikayla/scripts/-/raw/master/ci-discord-hook.sh
    - chmod +x ci-discord-hook.sh
    - /bin/sh ci-discord-hook.sh success $WEBHOOK_URL
  when: on_success

failure_notification:
  stage: notification
  script:
    - apk add curl git
    - wget https://gitlab.mdbook.me/mikayla/scripts/-/raw/master/ci-discord-hook.sh
    - chmod +x ci-discord-hook.sh
    - /bin/sh ci-discord-hook.sh failure $WEBHOOK_URL
  when: on_failure
