variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  FF_NETWORK_PER_BUILD: "true"

stages:
  - verify
  - build
  - notification


verify:
  stage: verify
  image: node:20-alpine
  script:
    - npm ci
    - npm run typecheck
    - npm test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success


build:
  stage: build
  image: docker:29.3.1-cli
  services:
    - docker:29.3.1-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker tag "$CI_REGISTRY_IMAGE:latest" "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success

success_notification:
  stage: notification
  image: alpine:3.20
  script:
    - apk add curl git
    - wget https://gitlab.mdbook.me/mikayla/scripts/-/raw/master/ci-discord-hook.sh
    - chmod +x ci-discord-hook.sh
    - /bin/sh ci-discord-hook.sh success $WEBHOOK_URL
  when: on_success

failure_notification:
  stage: notification
  image: alpine:3.20
  script:
    - apk add curl git
    - wget https://gitlab.mdbook.me/mikayla/scripts/-/raw/master/ci-discord-hook.sh
    - chmod +x ci-discord-hook.sh
    - /bin/sh ci-discord-hook.sh failure $WEBHOOK_URL
  when: on_failure
